name: Units CI

on: [push, pull_request]

jobs:
  test:
    name: Unit-Tests QA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install deps
        working-directory: ./frontend
        run: npm ci
      - name: Linting
        working-directory: ./frontend
        run: npm run lint
      - name: Testing
        working-directory: ./frontend
        run: npm test

  testback:
    stages:
      - setup
      - test

    variables:
      PYTHON_VERSION: "3.11"  # Укажите нужную версию Python

    before_script:
      - apt-get update -qy
      - apt-get install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-pip

    setup:
      stage: setup
      script:
        - python${PYTHON_VERSION} --version
        - pip${PYTHON_VERSION} install coverage

    test:
      stage: test
      working-directory: ./backend
      script:
        - coverage run -m unittest src/test_calculator.py
        - coverage report -m
