name: Units CI

on: [push, pull_request]

stages:
  - setup
  - test

jobs:
  test:
    name: Unit-Tests QA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install deps
        working-directory: ./frontend
        run: npm ci
      - name: Linting
        working-directory: ./frontend
        run: npm run lint
      - name: Testing
        working-directory: ./frontend
        run: npm test

  testback:
    name: Unit-Tests QA
    runs-on: ubuntu-latest

    variables:
      PYTHON_VERSION: "3.11"  # Укажите нужную версию Python

    steps:
      - name: Setup
        stage: setup
        run: |
          python${PYTHON_VERSION} --version
          pip${PYTHON_VERSION} install coverage

      - name: Test
        stage: test
        working-directory: ./backend
        run: |
          coverage run -m unittest src/test_calculator.py
          coverage report -m
