name: Units CI

on: [push, pull_request]

jobs:
  test:
    name: Unit-Tests QA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install deps
        working-directory: ./frontend
        run: npm ci
      - name: Linting
        working-directory: ./frontend
        run: npm run lint
      - name: Testing
        working-directory: ./frontend
        run: npm test
